import { sequelize } from "./config/db.js";
import { Product } from "./models/index.js";

const seed = async () => {
  try {
    await sequelize.authenticate();
    await sequelize.sync({ force: true });

    console.log("Insertando datos de prueba...");

    await Product.bulkCreate([
      {
        sku: "REM-BAT-M",
        nombre: "Remera Batman Talle M",
        precio_costo: 2500,
        precio_venta: 5000,
        stock_actual: 10,
        categoria: "Ropa",
      },
      {
        sku: "LAPIZ-HB",
        nombre: "Lápiz Negro HB",
        precio_costo: 50,
        precio_venta: 200,
        stock_actual: 50,
        categoria: "Libreria",
      },
      {
        sku: "REM-SPIDER-L",
        nombre: "Remera Spiderman Talle L",
        precio_costo: 2800,
        precio_venta: 5500,
        stock_actual: 15,
        categoria: "Ropa",
      },
      {
        sku: "PANT-JEAN-M",
        nombre: "Pantalón Jean Talle M",
        precio_costo: 4500,
        precio_venta: 9000,
        stock_actual: 8,
        categoria: "Ropa",
      },
      {
        sku: "BUZO-NIKE-XL",
        nombre: "Buzo Nike Talle XL",
        precio_costo: 6000,
        precio_venta: 12000,
        stock_actual: 5,
        categoria: "Ropa",
      },
      {
        sku: "CAMP-ADIDAS-M",
        nombre: "Campera Adidas Talle M",
        precio_costo: 8000,
        precio_venta: 16000,
        stock_actual: 4,
        categoria: "Ropa",
      },
      {
        sku: "GORRA-ROJA",
        nombre: "Gorra Roja Ajustable",
        precio_costo: 1500,
        precio_venta: 3000,
        stock_actual: 20,
        categoria: "Ropa",
      },
      {
        sku: "MEDIA-DEPORT-PACK",
        nombre: "Pack 3 Medias Deportivas",
        precio_costo: 800,
        precio_venta: 1800,
        stock_actual: 30,
        categoria: "Ropa",
      },
      {
        sku: "SHORT-VERANO-S",
        nombre: "Short de Verano Talle S",
        precio_costo: 2000,
        precio_venta: 4200,
        stock_actual: 12,
        categoria: "Ropa",
      },
      {
        sku: "ZAPAT-CONVERSE-40",
        nombre: "Zapatillas Converse Talle 40",
        precio_costo: 10000,
        precio_venta: 20000,
        stock_actual: 6,
        categoria: "Ropa",
      },
      {
        sku: "CUAD-TAPA-DURA",
        nombre: "Cuaderno Tapa Dura A4 100 hojas",
        precio_costo: 350,
        precio_venta: 800,
        stock_actual: 40,
        categoria: "Libreria",
      },
      {
        sku: "LAPIZ-2B",
        nombre: "Lápiz Negro 2B",
        precio_costo: 55,
        precio_venta: 220,
        stock_actual: 60,
        categoria: "Libreria",
      },
      {
        sku: "GOMA-BLANCA",
        nombre: "Goma de Borrar Blanca",
        precio_costo: 30,
        precio_venta: 150,
        stock_actual: 80,
        categoria: "Libreria",
      },
      {
        sku: "LAPICERA-AZUL",
        nombre: "Lapicera Azul",
        precio_costo: 80,
        precio_venta: 300,
        stock_actual: 45,
        categoria: "Libreria",
      },
      {
        sku: "RESALTADOR-AMARILLO",
        nombre: "Resaltador Amarillo",
        precio_costo: 120,
        precio_venta: 450,
        stock_actual: 35,
        categoria: "Libreria",
      },
      {
        sku: "CARPETA-3ANILLOS",
        nombre: "Carpeta 3 Anillos A4",
        precio_costo: 450,
        precio_venta: 1000,
        stock_actual: 25,
        categoria: "Libreria",
      },
      {
        sku: "TIJERA-ESCOLAR",
        nombre: "Tijera Escolar Punta Roma",
        precio_costo: 280,
        precio_venta: 650,
        stock_actual: 30,
        categoria: "Libreria",
      },
      {
        sku: "PEGAMENTO-STICK",
        nombre: "Pegamento en Barra 20g",
        precio_costo: 150,
        precio_venta: 400,
        stock_actual: 50,
        categoria: "Libreria",
      },
      {
        sku: "REGLA-30CM",
        nombre: "Regla 30cm Transparente",
        precio_costo: 90,
        precio_venta: 350,
        stock_actual: 40,
        categoria: "Libreria",
      },
      {
        sku: "MARCADOR-NEGRO",
        nombre: "Marcador Permanente Negro",
        precio_costo: 200,
        precio_venta: 550,
        stock_actual: 28,
        categoria: "Libreria",
      },
      {
        sku: "AUTO-CTRL-REMOTO",
        nombre: "Auto a Control Remoto",
        precio_costo: 3500,
        precio_venta: 7500,
        stock_actual: 10,
        categoria: "Juguete",
      },
      {
        sku: "MUNECA-BARBIE",
        nombre: "Muñeca Barbie Clásica",
        precio_costo: 4000,
        precio_venta: 8500,
        stock_actual: 8,
        categoria: "Juguete",
      },
      {
        sku: "LEGO-CIUDAD",
        nombre: "Lego Set Ciudad 200 piezas",
        precio_costo: 5500,
        precio_venta: 11000,
        stock_actual: 7,
        categoria: "Juguete",
      },
      {
        sku: "PELOTA-FUTBOL",
        nombre: "Pelota de Fútbol N°5",
        precio_costo: 2500,
        precio_venta: 5200,
        stock_actual: 15,
        categoria: "Juguete",
      },
      {
        sku: "ROMPECABEZAS-1000",
        nombre: "Rompecabezas 1000 Piezas",
        precio_costo: 1800,
        precio_venta: 3800,
        stock_actual: 12,
        categoria: "Juguete",
      },
      {
        sku: "FIGURA-ACCION-HULK",
        nombre: "Figura de Acción Hulk",
        precio_costo: 3200,
        precio_venta: 6800,
        stock_actual: 9,
        categoria: "Juguete",
      },
      {
        sku: "MONOPOLY-CLASICO",
        nombre: "Juego Monopoly Clásico",
        precio_costo: 4500,
        precio_venta: 9500,
        stock_actual: 6,
        categoria: "Juguete",
      },
      {
        sku: "YOYO-PROFESIONAL",
        nombre: "Yoyo Profesional",
        precio_costo: 800,
        precio_venta: 1800,
        stock_actual: 20,
        categoria: "Juguete",
      },
      {
        sku: "PELUCHE-OSO-50CM",
        nombre: "Peluche Osito 50cm",
        precio_costo: 2000,
        precio_venta: 4500,
        stock_actual: 14,
        categoria: "Juguete",
      },
      {
        sku: "PATINETA-INFANTIL",
        nombre: "Patineta Infantil",
        precio_costo: 3800,
        precio_venta: 7800,
        stock_actual: 5,
        categoria: "Juguete",
      },
      {
        sku: "PISTOLA-NERF",
        nombre: "Pistola Nerf con Dardos",
        precio_costo: 2800,
        precio_venta: 5800,
        stock_actual: 11,
        categoria: "Juguete",
      },
      {
        sku: "SLIME-COLORES",
        nombre: "Slime Pack 6 Colores",
        precio_costo: 900,
        precio_venta: 2000,
        stock_actual: 25,
        categoria: "Juguete",
      },
    ]);

    console.log("Productos Cargados...");
    process.exit();
  } catch (error) {
    console.error("No se pudo cargar los productos", error);
    process.exit(1);
  }
};

seed();
